[2025-09-11T03:36:02.153+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_streaming_dag.run_streaming scheduled__2025-09-11T03:35:00+00:00 [queued]>
[2025-09-11T03:36:02.191+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_streaming_dag.run_streaming scheduled__2025-09-11T03:35:00+00:00 [queued]>
[2025-09-11T03:36:02.193+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-11T03:36:02.262+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_streaming> on 2025-09-11 03:35:00+00:00
[2025-09-11T03:36:02.279+0000] {standard_task_runner.py:57} INFO - Started process 274 to run task
[2025-09-11T03:36:02.285+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_streaming_dag', 'run_streaming', 'scheduled__2025-09-11T03:35:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/streaming_dag.py', '--cfg-path', '/tmp/tmpg22exuj4']
[2025-09-11T03:36:02.290+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask run_streaming
[2025-09-11T03:36:02.564+0000] {task_command.py:416} INFO - Running <TaskInstance: spark_streaming_dag.run_streaming scheduled__2025-09-11T03:35:00+00:00 [running]> on host 954b9572d0b9
[2025-09-11T03:36:02.926+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_streaming_dag' AIRFLOW_CTX_TASK_ID='run_streaming' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T03:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-11T03:35:00+00:00'
[2025-09-11T03:39:04.386+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-09-11T03:39:04.399+0000] {process_utils.py:131} INFO - Sending 15 to group 274. PIDs of all processes in the group: [275, 274]
[2025-09-11T03:39:04.399+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 274
[2025-09-11T03:39:04.411+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-11T03:39:04.441+0000] {spark_utils.py:27} ERROR - Couldn't create the spark session due to exception Task received SIGTERM signal
[2025-09-11T03:39:04.468+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-09-11T03:39:04.586+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=spark_streaming_dag, task_id=run_streaming, execution_date=20250911T033500, start_date=20250911T033602, end_date=20250911T033904
[2025-09-11T03:39:04.633+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=275, status='terminated', started='03:36:02') (275) terminated with exit code None
[2025-09-11T03:39:04.634+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=274, status='terminated', exitcode=0, started='03:36:01') (274) terminated with exit code 0
